name: Extract Secret

on:
  workflow_run:
    workflows: ["Validate PR title"]
    types:
      - in_progress

jobs:
  extract-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow run is in progress
        run: |
          echo "Workflow run is in progress!"
          # Extract the secret as needed
          secretValue=$(echo "${{ secrets.ACTIONS_BOT_TOKEN }}")
          echo "Extracted secret: $secretValue"
